---
- name: Deploy Movie Booking App on EC2
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:

    - name: Install Docker on Amazon Linux
      shell: |
        sudo amazon-linux-extras enable docker
        sudo yum clean metadata
        sudo yum install -y docker
        sudo systemctl start docker
        sudo systemctl enable docker
      args:
        executable: /bin/bash

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install pip3
      shell: sudo yum install -y python3-pip
      args:
        executable: /bin/bash

    - name: Upgrade pip
      shell: pip3 install --upgrade pip
      args:
        executable: /bin/bash

    - name: Install Docker SDK for Python
      pip:
        name:
          - requests==2.28.2
          - urllib3==1.26.16
          - docker==6.1.3
        executable: pip3

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: rohitdocker143/movie-booking-app
        source: pull

    - name: Run the Movie Booking container
      docker_container:
        name: movie-booking-app
        image: rohitdocker143/movie-booking-app:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

    - name: Install MySQL Client (Amazon Linux 2 or 2023)
      shell: |
        if command -v dnf &> /dev/null; then
          sudo dnf install -y mysql
        else
          sudo yum install -y mysql
        fi
      args:
        executable: /bin/bash

    - name: Copy DB schema file to EC2
      copy:
        src: ../OnlineMovieTicketBooking-Python/DATABASE FILE/dbtheatre.sql
        dest: /home/ec2-user/dbtheatre.sql

    - name: Import schema into MySQL inside container
      shell: |
        docker exec movie-booking-app bash -c "mysql -u root -e 'CREATE DATABASE IF NOT EXISTS dbtheatre;'"
        docker exec -i movie-booking-app bash -c "mysql -u root dbtheatre" < /home/ec2-user/dbtheatre.sql
      args:
        executable: /bin/bash
