---
- name: Deploy Movie Booking App on EC2
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:

    - name: Install Docker on Amazon Linux 2
      shell: |
        sudo amazon-linux-extras enable docker
        sudo yum clean metadata
        sudo yum install -y docker
        sudo systemctl start docker
        sudo systemctl enable docker
      args:
        executable: /bin/bash

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install pip3
      shell: sudo yum install -y python3-pip
      args:
        executable: /bin/bash

    - name: Upgrade pip
      shell: pip3 install --upgrade pip
      args:
        executable: /bin/bash

    - name: Install Docker SDK for Python
      pip:
        name:
          - requests==2.28.2
          - urllib3==1.26.16
          - docker==6.1.3
        executable: pip3

    - name: Install MySQL Client (Amazon Linux 2)
      shell: |
        sudo yum install -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
        sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
        sudo yum install -y mysql
      args:
        executable: /bin/bash


    - name: Pull Docker image from Docker Hub
      docker_image:
        name: rohitdocker143/movie-booking-app
        source: pull

    - name: Run the Movie Booking container
      docker_container:
        name: movie-booking-app
        image: rohitdocker143/movie-booking-app:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

    - name: Copy DB schema file to EC2
      copy:
        src: ../OnlineMovieTicketBooking-Python/DATABASE FILE/dbtheatre.sql
        dest: /home/ec2-user/dbtheatre.sql

    - name: Import schema into MySQL from EC2 host
      shell: |
        mysql -u root -e 'CREATE DATABASE IF NOT EXISTS dbtheatre;'
        mysql -u root dbtheatre < /home/ec2-user/dbtheatre.sql
      args:
        executable: /bin/bash
