---
- name: Deploy Movie Booking App on EC2
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:

    - name: Install Docker on Amazon Linux 2
      shell: |
        sudo amazon-linux-extras enable docker
        sudo yum clean metadata
        sudo yum install -y docker
        sudo systemctl start docker
        sudo systemctl enable docker
      args:
        executable: /bin/bash

    - name: Install pip3 using shell (fix for yum detection issue)
      shell: |
        sudo yum install -y python3-pip
      args:
        executable: /bin/bash

    - name: Install required Python packages for Docker modules
      pip:
        name:
          - requests==2.28.2
          - urllib3==1.26.16
          - docker==6.1.3

    - name: Pull Docker image
      docker_image:
        name: rohitdocker143/movie-booking-app
        source: pull

    - name: Run Movie Booking container
      docker_container:
        name: movie-booking-app
        image: rohitdocker143/movie-booking-app:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
