---
- name: Deploy Movie Booking App on EC2
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:

    - name: Install Docker on Amazon Linux 2
      shell: |
        sudo amazon-linux-extras enable docker
        sudo yum clean metadata
        sudo yum install -y docker
        sudo systemctl start docker
        sudo systemctl enable docker
      args:
        executable: /bin/bash

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install pip3
      shell: sudo yum install -y python3-pip
      args:
        executable: /bin/bash

    - name: Upgrade pip
      shell: pip3 install --upgrade pip
      args:
        executable: /bin/bash

    - name: Install Docker SDK for Python
      pip:
        name:
          - requests==2.28.2
          - urllib3==1.26.16
          - docker==6.1.3
        executable: pip3

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: rohitdocker143/movie-booking-app
        source: pull

    - name: Run the Movie Booking container
      docker_container:
        name: movie-booking-app
        image: rohitdocker143/movie-booking-app:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

    - name: Install MySQL Client (needed for DB import)
      yum:
        name: mysql
        state: present

    - name: Copy DB schema file to EC2
      copy:
        src: ../OnlineMovieTicketBooking-Python/DATABASE FILE/dbtheatre.sql
        dest: /home/ec2-user/dbtheatre.sql

    - name: Create database if not exists (from host into container)
      shell: |
        docker exec movie-booking-app sh -c "mysql -u root -e 'CREATE DATABASE IF NOT EXISTS dbtheatre;'"
      args:
        executable: /bin/bash

    - name: Import DB schema into container MySQL
      shell: |
        docker cp /home/ec2-user/dbtheatre.sql movie-booking-app:/dbtheatre.sql
        docker exec movie-booking-app sh -c "mysql -u root dbtheatre < /dbtheatre.sql"
      args:
        executable: /bin/bash
